package uk.gegc.kidsgptbackend.features.consent.domain;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;
import uk.gegc.kidsgptbackend.features.consent.domain.model.*;
import uk.gegc.kidsgptbackend.features.consent.domain.repository.ConsentLedgerRepository;
import uk.gegc.kidsgptbackend.features.consent.domain.repository.ParentVerificationRepository;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@ActiveProfiles("test")
class ParentVerificationRepositoryTest {

    @Autowired
    private ParentVerificationRepository parentVerificationRepository;

    @Autowired
    private org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager entityManager;

    private UUID testParentId;
    private UUID testVerificationId;

    @BeforeEach
    void setUp() {
        testParentId = UUID.randomUUID();
        testVerificationId = UUID.randomUUID();
    }

    @Test
    void findById_BasicHappyPathForPersistingAndFetchingById() {
        // Given: Create a ParentVerification entity
        ParentVerification verification = ParentVerification.builder()
                .parentId(testParentId)
                .verificationMethod(VerificationMethod.EMAIL)
                .verificationStatus(VerificationStatus.VERIFIED)
                .contactInfoHash("test@example.com".getBytes())
                .verificationCodeHash("123456".getBytes())
                .attemptCount(1)
                .expiresAt(LocalDateTime.now().plusDays(1))
                .verifiedAt(LocalDateTime.now())
                .ipAddress("192.168.1.1")
                .userAgent("Mozilla/5.0")
                .build();

        // When: Persist the entity
        ParentVerification savedVerification = parentVerificationRepository.save(verification);
        entityManager.flush();
        entityManager.clear();

        // Then: Verify the entity was persisted correctly
        assertNotNull(savedVerification, "Saved verification should not be null");
        assertNotNull(savedVerification.getVerificationId(), "Verification ID should be auto-generated");
        assertEquals(testParentId, savedVerification.getParentId(), "Parent ID should match");
        assertEquals(VerificationMethod.EMAIL, savedVerification.getVerificationMethod(), "Verification method should match");
        assertEquals(VerificationStatus.VERIFIED, savedVerification.getVerificationStatus(), "Verification status should match");
        assertEquals(1, savedVerification.getAttemptCount(), "Attempt count should match");
        assertNotNull(savedVerification.getCreatedAt(), "Created at should be auto-populated");

        // When: Fetch the entity by ID
        Optional<ParentVerification> foundVerification = parentVerificationRepository.findById(savedVerification.getVerificationId());

        // Then: Verify the entity was retrieved correctly
        assertTrue(foundVerification.isPresent(), "Verification should be found by ID");
        ParentVerification retrievedVerification = foundVerification.get();
        assertEquals(savedVerification.getVerificationId(), retrievedVerification.getVerificationId(), "Retrieved verification ID should match");
        assertEquals(testParentId, retrievedVerification.getParentId(), "Retrieved parent ID should match");
        assertEquals(VerificationMethod.EMAIL, retrievedVerification.getVerificationMethod(), "Retrieved verification method should match");
        assertEquals(VerificationStatus.VERIFIED, retrievedVerification.getVerificationStatus(), "Retrieved verification status should match");
        assertEquals(1, retrievedVerification.getAttemptCount(), "Retrieved attempt count should match");
        assertNotNull(retrievedVerification.getCreatedAt(), "Retrieved created at should not be null");
        assertNotNull(retrievedVerification.getVerifiedAt(), "Retrieved verified at should not be null");
        assertEquals("192.168.1.1", retrievedVerification.getIpAddress(), "Retrieved IP address should match");
        assertEquals("Mozilla/5.0", retrievedVerification.getUserAgent(), "Retrieved user agent should match");
    }

    @Test
    void findById_NonExistentId_ReturnsEmptyOptional() {
        // Given: A non-existent verification ID
        UUID nonExistentId = UUID.randomUUID();

        // When: Try to find by non-existent ID
        Optional<ParentVerification> foundVerification = parentVerificationRepository.findById(nonExistentId);

        // Then: Should return empty optional
        assertFalse(foundVerification.isPresent(), "Should return empty optional for non-existent ID");
    }

    @Test
    void findById_VerifyAutoGeneratedFields() {
        // Given: Create a ParentVerification without setting createdAt
        ParentVerification verification = ParentVerification.builder()
                .parentId(testParentId)
                .verificationMethod(VerificationMethod.EMAIL)
                .verificationStatus(VerificationStatus.PENDING)
                .contactInfoHash("test@example.com".getBytes())
                .verificationCodeHash("123456".getBytes())
                .attemptCount(null) // Test auto-population
                .expiresAt(LocalDateTime.now().plusDays(1))
                .ipAddress("192.168.1.1")
                .userAgent("Mozilla/5.0")
                .build();

        // When: Persist and retrieve the entity
        ParentVerification savedVerification = parentVerificationRepository.save(verification);
        entityManager.flush();
        entityManager.clear();

        Optional<ParentVerification> foundVerification = parentVerificationRepository.findById(savedVerification.getVerificationId());

        // Then: Verify auto-generated fields
        assertTrue(foundVerification.isPresent(), "Verification should be found");
        ParentVerification retrievedVerification = foundVerification.get();
        
        // Verify attemptCount was auto-populated to 0
        assertEquals(0, retrievedVerification.getAttemptCount(), "Attempt count should be auto-populated to 0");
        
        // Verify createdAt was auto-populated
        assertNotNull(retrievedVerification.getCreatedAt(), "Created at should be auto-populated");
        
        // Verify the timestamp is reasonable (within a few seconds of now)
        LocalDateTime now = LocalDateTime.now(ZoneOffset.UTC);
        assertTrue(retrievedVerification.getCreatedAt().isAfter(now.minusSeconds(10)), 
                "Created at should be recent");
        assertTrue(retrievedVerification.getCreatedAt().isBefore(now.plusSeconds(10)), 
                "Created at should not be in the future");
    }
} 