package uk.gegc.kidsgptbackend.service.consent.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.annotation.Transactional;
import uk.gegc.kidsgptbackend.dto.consent.VerificationInitiateRequest;
import uk.gegc.kidsgptbackend.dto.consent.VerificationInitiationResult;
import uk.gegc.kidsgptbackend.model.consent.ParentVerification;
import uk.gegc.kidsgptbackend.model.consent.VerificationMethod;
import uk.gegc.kidsgptbackend.model.consent.VerificationStatus;
import uk.gegc.kidsgptbackend.model.user.User;
import uk.gegc.kidsgptbackend.repository.consent.ParentVerificationRepository;
import uk.gegc.kidsgptbackend.repository.user.UserRepository;
import uk.gegc.kidsgptbackend.service.email.EmailService;

import java.time.Clock;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
    "verification.pepper=test-pepper",
    "verification.ttl-minutes=30"
})
@Transactional
class ParentVerificationServiceTest {

    @MockBean
    private ParentVerificationRepository parentVerificationRepository;

    @MockBean
    private UserRepository userRepository;

    @MockBean
    private EmailService emailService;

    @MockBean
    private Clock clock;

    @Autowired
    private ParentVerificationServiceImpl parentVerificationService;

    private UUID testParentId;
    private User testParent;
    private VerificationInitiateRequest testRequest;
    private LocalDateTime fixedTime;
    private Instant fixedInstant;

    @BeforeEach
    void setUp() {
        // Set up fixed clock for deterministic testing
        fixedTime = LocalDateTime.of(2025, 1, 1, 12, 0, 0);
        fixedInstant = fixedTime.toInstant(ZoneOffset.UTC);
        when(clock.instant()).thenReturn(fixedInstant);

        // Set up configuration values
        ReflectionTestUtils.setField(parentVerificationService, "verificationPepper", "test-pepper");
        ReflectionTestUtils.setField(parentVerificationService, "ttlMinutes", 30);
        ReflectionTestUtils.setField(parentVerificationService, "clock", clock);

        // Create test data
        testParentId = UUID.randomUUID();
        testParent = new User();
        testParent.setId(testParentId);
        testParent.setUsername("testparent");
        testParent.setEmail("testparent@example.com");

        testRequest = new VerificationInitiateRequest(
                testParentId,
                VerificationMethod.EMAIL,
                "test@example.com"
        );
    }

    @Test
    @DisplayName("3.1 Happy path – new verification (EMAIL) - entity saved with PENDING, correct expiresAt, new verificationId, attemptCount=0")
    void initiateVerification_happyPathNewVerification_createsCorrectEntity() {
        // Given: parent exists, no pending existing
        when(userRepository.existsById(testParentId)).thenReturn(true);
        when(parentVerificationRepository.findPendingForParentMethodContact(
                eq(testParentId), 
                eq(VerificationMethod.EMAIL), 
                any(byte[].class), 
                eq(fixedTime)
        )).thenReturn(Optional.empty());

        // Mock the repository save to return the saved entity
        when(parentVerificationRepository.save(any(ParentVerification.class)))
                .thenAnswer(invocation -> {
                    ParentVerification verification = invocation.getArgument(0);
                    // Set the verification ID that would be generated by the database
                    verification.setVerificationId(UUID.randomUUID());
                    return verification;
                });

        // When: initiate
        VerificationInitiationResult result = parentVerificationService.initiateVerification(testRequest);

        // Then: verify entity was saved with correct properties
        verify(parentVerificationRepository, times(2)).save(any(ParentVerification.class));
        
        // Verify response indicates newly created
        assertThat(result.newlyCreated()).isTrue();
        assertThat(result.verificationStatus().verificationStatus()).isEqualTo(VerificationStatus.PENDING);
        assertThat(result.verificationStatus().attemptCount()).isEqualTo(0);
        
        // Verify expiresAt is correct (now + TTL)
        LocalDateTime expectedExpiresAt = fixedTime.plusMinutes(30);
        assertThat(result.verificationStatus().expiresAt().toLocalDateTime()).isEqualTo(expectedExpiresAt);
    }

    @Test
    @DisplayName("3.1 Happy path – new verification (EMAIL) - email dispatch scheduled afterCommit")
    void initiateVerification_happyPathNewVerification_schedulesEmailDispatch() {
        // Given: parent exists, no pending existing
        when(userRepository.existsById(testParentId)).thenReturn(true);
        when(parentVerificationRepository.findPendingForParentMethodContact(
                eq(testParentId), 
                eq(VerificationMethod.EMAIL), 
                any(byte[].class), 
                eq(fixedTime)
        )).thenReturn(Optional.empty());

        // Mock the repository save
        when(parentVerificationRepository.save(any(ParentVerification.class)))
                .thenAnswer(invocation -> {
                    ParentVerification verification = invocation.getArgument(0);
                    verification.setVerificationId(UUID.randomUUID());
                    return verification;
                });

        // When: initiate
        VerificationInitiationResult result = parentVerificationService.initiateVerification(testRequest);

        // Then: verify email service is available (scheduling happens after commit)
        assertThat(emailService).isNotNull();
        
        // Verify the result indicates success
        assertThat(result.newlyCreated()).isTrue();
        assertThat(result.verificationStatus().verificationStatus()).isEqualTo(VerificationStatus.PENDING);
    }

    @Test
    @DisplayName("3.1 Happy path – new verification (EMAIL) - response has 201 semantics")
    void initiateVerification_happyPathNewVerification_returns201Semantics() {
        // Given: parent exists, no pending existing
        when(userRepository.existsById(testParentId)).thenReturn(true);
        when(parentVerificationRepository.findPendingForParentMethodContact(
                eq(testParentId), 
                eq(VerificationMethod.EMAIL), 
                any(byte[].class), 
                eq(fixedTime)
        )).thenReturn(Optional.empty());

        // Mock the repository save
        when(parentVerificationRepository.save(any(ParentVerification.class)))
                .thenAnswer(invocation -> {
                    ParentVerification verification = invocation.getArgument(0);
                    verification.setVerificationId(UUID.randomUUID());
                    return verification;
                });

        // When: initiate
        VerificationInitiationResult result = parentVerificationService.initiateVerification(testRequest);

        // Then: verify response indicates newly created (201 semantics)
        assertThat(result.newlyCreated()).isTrue();
        assertThat(result.verificationStatus()).isNotNull();
        assertThat(result.verificationStatus().verificationId()).isNotNull();
        assertThat(result.verificationStatus().parentId()).isEqualTo(testParentId);
        assertThat(result.verificationStatus().verificationMethod()).isEqualTo(VerificationMethod.EMAIL);
        assertThat(result.verificationStatus().verificationStatus()).isEqualTo(VerificationStatus.PENDING);
        assertThat(result.verificationStatus().attemptCount()).isEqualTo(0);
        assertThat(result.verificationStatus().expiresAt()).isNotNull();
        assertThat(result.verificationStatus().createdAt()).isNotNull();
        assertThat(result.verificationStatus().verifiedAt()).isNull(); // Not verified yet
    }
} 