name: Continuous Integration

# 1. Trigger on pushes & PRs to main
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kidsgptdb   # ✅ must exist before the app starts
          MYSQL_USER: bestuser
          MYSQL_PASSWORD: bestuser
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    # Environment variables that Spring picks up via ${...}
    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/kidsgptdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: bestuser
      DB_PASSWORD: bestuser

      TEST_DB_URL: jdbc:mysql://127.0.0.1:3306/kidsgptdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      TEST_DB_USERNAME: bestuser
      TEST_DB_PASSWORD: bestuser

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait for MySQL to accept connections
        run: |
          until mysqladmin ping -h 127.0.0.1 -ubestuser -pbestuser --silent; do
            echo "Waiting for MySQL ..."
            sleep 5
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build & test
        run: ./mvnw --batch-mode clean verify